FROM opensuse:tumbleweed
MAINTAINER Michael Stroeder <michael@stroeder.com>

# install latest updates to be on the safe side
RUN zypper --non-interactive dup --auto-agree-with-licenses --no-allow-vendor-change --no-recommends

# install packages from openSUSE standard repo
RUN zypper --non-interactive install --no-confirm --no-recommends ca-certificates ca-certificates-mozilla
# Python3 and some modules
RUN zypper --non-interactive install --no-confirm --no-recommends python3 python3-virtualenv python3-setuptools python3-asn1crypto python3-xlwt python3-paramiko python3-bcrypt python3-pyasn1-modules python3-dnspython

# add repo home:stroeder:iam
RUN zypper --non-interactive addrepo --enable --refresh https://download.opensuse.org/repositories/home:/stroeder:/iam/openSUSE_Tumbleweed/home:stroeder:iam.repo
# refresh repo cache
RUN zypper --non-interactive --gpg-auto-import-keys refresh
# install non-standard Python modules
RUN zypper --non-interactive install --no-confirm --no-recommends python3-ldap0 web2ldap

# Override web2ldap's config module files
ADD --chown=root:root web2ldapcnf/*.py /etc/web2ldap/web2ldapcnf/
RUN chmod 0755 /etc/web2ldap/web2ldapcnf
RUN chmod 0644 /etc/web2ldap/web2ldapcnf/*.py
RUN ls -al /etc/web2ldap/web2ldapcnf/

# run web2ldap and expose its TCP port 1760 for web access
USER web2ldap
EXPOSE 1760
CMD /usr/bin/web2ldap 0.0.0.0 1760
