FROM opensuse:tumbleweed
MAINTAINER Michael Stroeder <michael@stroeder.com>

# install latest updates to be on the safe side
RUN zypper --non-interactive dup --auto-agree-with-licenses --no-allow-vendor-change --no-recommends

# install packages from openSUSE standard repo
RUN zypper --non-interactive install --no-confirm --no-recommends ca-certificates ca-certificates-mozilla
# Python2 and some modules
RUN zypper --non-interactive install --no-confirm --no-recommends python python2-virtualenv python2-setuptools python-pyweblib python-ipaddress python2-asn1crypto python2-xlwt python2-paramiko python2-certifi python2-bcrypt python2-pyasn1-modules python2-dnspython

# add AE-DIR repo
RUN zypper --non-interactive addrepo --enable --refresh https://download.opensuse.org/repositories/home:/stroeder:/AE-DIR/openSUSE_Tumbleweed/home:stroeder:AE-DIR.repo
# refresh repo cache
RUN zypper --non-interactive --gpg-auto-import-keys refresh
# install non-standard Python modules
RUN zypper --non-interactive install --no-confirm --no-recommends python-ldap0

# install web2ldap in virtual env
RUN virtualenv-2.7 -p python2.7 --system-site-packages /opt/web2ldap
RUN /opt/web2ldap/bin/pip2 install --no-cache-dir --upgrade-strategy=only-if-needed --find-links https://www.web2ldap.de/download.html web2ldap

# Override web2ldap's config module files
ADD --chown=root:root web2ldapcnf/*.py /opt/web2ldap/etc/web2ldap/web2ldapcnf/
RUN chmod 0755 /opt/web2ldap/etc/web2ldap/web2ldapcnf
RUN chmod 0644 /opt/web2ldap/etc/web2ldap/web2ldapcnf/*.py
RUN ls -al /opt/web2ldap/etc/web2ldap/web2ldapcnf/

# run web2ldap and expose its TCP port 1760 for web access
RUN groupadd -r -g 1760 web2ldap
RUN useradd -r -u 1760 -g 1760 web2ldap
USER web2ldap
EXPOSE 1760
CMD /opt/web2ldap/bin/web2ldap 0.0.0.0 1760
