FROM debian:bullseye-slim
MAINTAINER Michael Stroeder <michael@stroeder.com>

ENV DEBIAN_FRONTEND=noninteractive

# install latest updates to be on the safe side
RUN apt update && apt full-upgrade -f -y

# install packages from standard repo
RUN apt-get install --yes --quiet --no-install-recommends --option 'DPkg::Options=--force-confold' --option 'DPkg::Options=--force-confdef' wget apt-transport-https ca-certificates gnupg2

RUN wget -O /usr/share/keyrings/AE-DIR-project.gpg.key https://ae-dir.com/repo/debian/AE-DIR-project.gpg.key
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/AE-DIR-project.gpg.key] https://ae-dir.com/repo/debian/bullseye bullseye main" > /etc/apt/sources.list.d/AE-DIR.list
RUN apt-get update
RUN apt-get install --yes --quiet --no-install-recommends --option 'DPkg::Options=--force-confold' --option 'DPkg::Options=--force-confdef' libsasl2-modules python3-defusedxml python3-prometheus-client python3-dnspython web2ldap

# copy the config files shipped with Debian package to /etc/web2ldap
RUN cp -av /usr/etc/web2ldap /etc/web2ldap
# Override web2ldap's config module files
ADD --chown=root:root web2ldapcnf/*.py /etc/web2ldap/web2ldapcnf/
RUN chmod 0755 /etc/web2ldap/web2ldapcnf
RUN chmod 0644 /etc/web2ldap/web2ldapcnf/*.py

# run web2ldap and expose its TCP port 1760 for web access
RUN groupadd -r -g 1760 web2ldap
RUN useradd -r -u 1760 -g 1760 web2ldap
USER web2ldap
EXPOSE 1760
CMD /usr/bin/web2ldap 0.0.0.0 1760
