FROM opensuse:tumbleweed
MAINTAINER Michael Stroeder <michael@stroeder.com>

# install latest updates to be on the safe side
RUN zypper --non-interactive dup --auto-agree-with-licenses --no-allow-vendor-change --no-recommends

# install packages from openSUSE standard repo
RUN zypper --non-interactive install --no-confirm --no-recommends ca-certificates ca-certificates-mozilla
# Python2 and some modules
RUN zypper --non-interactive install --no-confirm --no-recommends python python2-virtualenv python2-setuptools python-pyweblib python-ipaddress python2-asn1crypto python2-xlwt python2-paramiko python2-certifi python2-bcrypt python2-pyasn1-modules python2-dnspython

# add AE-DIR repo
RUN zypper --non-interactive addrepo --enable --refresh https://download.opensuse.org/repositories/home:/stroeder:/AE-DIR/openSUSE_Tumbleweed/home:stroeder:AE-DIR.repo
# refresh repo cache
RUN zypper --non-interactive --gpg-auto-import-keys refresh
# install non-standard Python modules
RUN zypper --non-interactive install --no-confirm --no-recommends web2ldap

# Override web2ldap's config module files
ADD --chown=root:root web2ldapcnf/*.py /usr/lib/python2.7/site-packages/web2ldapcnf/
ADD --chown=root:root web2ldapcnf/plugins/*.py /usr/lib/python2.7/site-packages/web2ldapcnf/plugins/
RUN rm /usr/lib/python2.7/site-packages/web2ldapcnf/*.py? /usr/lib/python2.7/site-packages/web2ldapcnf/plugins/*.py?
RUN chmod a+rx /usr/lib/python2.7/site-packages/web2ldapcnf /usr/lib/python2.7/site-packages/web2ldapcnf/plugins
RUN chmod -R a+r /usr/lib/python2.7/site-packages/web2ldapcnf
RUN ls -al /usr/lib/python2.7/site-packages/web2ldapcnf/*

# run web2ldap and expose its TCP port 1760 for web access
USER web2ldap
EXPOSE 1760
CMD /usr/bin/web2ldap 0.0.0.0 1760
