# -*- coding: utf-8 -*-

countries = (
  (u'',u'0',u'- not set -'),
  (u'AD',u'20', u'Andorra'),
  (u'AE',u'784',u'United Arab Emirates'),
  (u'AF',u'4',  u'Afghanistan'),
  (u'AG',u'28', u'Antigua and Barbuda'),
  (u'AI',u'660',u'Anguilla'),
  (u'AL',u'8',  u'Albania'),
  (u'AM',u'51', u'Armenia'),
  (u'AN',u'530',u'Netherlands Antilles'),
  (u'AO',u'24', u'Angola'),
  (u'AQ',u'10', u'Antarctica'),
  (u'AR',u'32', u'Argentina'),
  (u'AS',u'16', u'American Samoa'),
  (u'AT',u'40', u'Austria'),
  (u'AU',u'36', u'Australia'),
  (u'AW',u'533',u'Aruba'),
  (u'AX',u'248',u'Åland Islands'),
  (u'AZ',u'31', u'Azerbaijan'),
  (u'BA',u'70', u'Bosnia and Herzegovina'),
  (u'BB',u'52', u'Barbados'),
  (u'BD',u'50', u'Bangladesh'),
  (u'BE',u'56', u'Belgium'),
  (u'BF',u'854',u'Burkina Faso'),
  (u'BG',u'100',u'Bulgaria'),
  (u'BH',u'48', u'Bahrain'),
  (u'BI',u'108',u'Burundi'),
  (u'BJ',u'204',u'Benin'),
  (u'BL',u'652',u'Saint Barthélemy'),
  (u'BM',u'60', u'Bermuda'),
  (u'BN',u'96', u'Brunei Darussalam'),
  (u'BO',u'68', u'Bolivia'),
  (u'BR',u'76', u'Brazil'),
  (u'BS',u'44', u'Bahamas, The'),
  (u'BT',u'64', u'Bhutan'),
  (u'BV',u'74', u'Bouvet Island'),
  (u'BW',u'72', u'Botswana'),
  (u'BY',u'112',u'Belarus'),
  (u'BZ',u'84', u'Belize'),
  (u'CA',u'124',u'Canada'),
  (u'CC',u'166',u'Cocos (Keeling) Islands'),
  (u'CD',u'180',u'Congo (DRC)'),
  (u'CF',u'140',u'Central African Republic'),
  (u'CG',u'178',u'Congo'),
  (u'CH',u'756',u'Switzerland'),
  (u'CI',u'384',u"Côte d'Ivoire"),
  (u'CK',u'184',u'Cook Islands'),
  (u'CL',u'152',u'Chile'),
  (u'CM',u'120',u'Cameroon'),
  (u'CN',u'156',u'China'),
  (u'CO',u'170',u'Colombia'),
  (u'CR',u'188',u'Costa Rica'),
  (u'CU',u'192',u'Cuba'),
  (u'CV',u'132',u'Cape Verde'),
  (u'CX',u'162',u'Christmas Island'),
  (u'CY',u'196',u'Cyprus'),
  (u'CZ',u'203',u'Czech Republic'),
  (u'DE',u'276',u'Germany'),
  (u'DJ',u'262',u'Djibouti'),
  (u'DK',u'208',u'Denmark'),
  (u'DM',u'212',u'Dominica'),
  (u'DO',u'214',u'Dominican Republic'),
  (u'DZ',u'12', u'Algeria'),
  (u'EC',u'218',u'Ecuador'),
  (u'EE',u'233',u'Estonia'),
  (u'EG',u'818',u'Egypt'),
  (u'EH',u'732',u'Western Sahara'),
  (u'ER',u'232',u'Eritrea'),
  (u'ES',u'724',u'Spain'),
  (u'ET',u'231',u'Ethiopia'),
  (u'FI',u'246',u'Finland'),
  (u'FJ',u'242',u'Fiji'),
  (u'FK',u'238',u'Falkland Islands (Islas Malvinas)'),
  (u'FM',u'583',u'Micronesia'),
  (u'FO',u'234',u'Faroe Islands'),
  (u'FR',u'250',u'France'),
  (u'GA',u'266',u'Gabon'),
  (u'GB',u'826',u'United Kingdom'),
  (u'GD',u'308',u'Grenada'),
  (u'GE',u'268',u'Georgia'),
  (u'GF',u'254',u'French Guiana'),
  (u'GG',u'831',u'Guernsey'),
  (u'GH',u'288',u'Ghana'),
  (u'GI',u'292',u'Gibraltar'),
  (u'GL',u'304',u'Greenland'),
  (u'GM',u'270',u'Gambia'),
  (u'GN',u'324',u'Guinea'),
  (u'GP',u'312',u'Guadeloupe'),
  (u'GQ',u'226',u'Equatorial Guinea'),
  (u'GR',u'300',u'Greece'),
  (u'GS',u'239',u'South Georgia and the South Sandwich Islands'),
  (u'GT',u'320',u'Guatemala'),
  (u'GU',u'316',u'Guam'),
  (u'GW',u'624',u'Guinea-Bissau'),
  (u'GY',u'328',u'Guyana'),
  (u'HK',u'344',u'Hong Kong'),
  (u'HM',u'334',u'Heard Island and McDonald Islands'),
  (u'HN',u'340',u'Honduras'),
  (u'HR',u'191',u'Croatia'),
  (u'HT',u'332',u'Haiti'),
  (u'HU',u'348',u'Hungary'),
  (u'ID',u'360',u'Indonesia'),
  (u'IE',u'372',u'Ireland'),
  (u'IL',u'376',u'Israel'),
  (u'IM',u'833',u'Isle of Man'),
  (u'IN',u'356',u'India'),
  (u'IO',u'86', u'British Indian Ocean Territory'),
  (u'IQ',u'368',u'Iraq'),
  (u'IR',u'364',u'Iran'),
  (u'IS',u'352',u'Iceland'),
  (u'IT',u'380',u'Italy'),
  (u'JE',u'832',u'Jersey'),
  (u'JM',u'388',u'Jamaica'),
  (u'JO',u'400',u'Jordan'),
  (u'JP',u'392',u'Japan'),
  (u'KE',u'404',u'Kenya'),
  (u'KG',u'417',u'Kyrgyzstan'),
  (u'KH',u'116',u'Cambodia'),
  (u'KI',u'296',u'Kiribati'),
  (u'KM',u'174',u'Comoros'),
  (u'KN',u'659',u'St. Kitts and Nevis'),
  (u'KP',u'408',u'Korea, North'),
  (u'KR',u'410',u'Korea'),
  (u'KW',u'414',u'Kuwait'),
  (u'KY',u'136',u'Cayman Islands'),
  (u'KZ',u'398',u'Kazakhstan'),
  (u'LA',u'418',u'Laos'),
  (u'LB',u'422',u'Lebanon'),
  (u'LC',u'662',u'St. Lucia'),
  (u'LI',u'438',u'Liechtenstein'),
  (u'LK',u'144',u'Sri Lanka'),
  (u'LR',u'430',u'Liberia'),
  (u'LS',u'426',u'Lesotho'),
  (u'LT',u'440',u'Lithuania'),
  (u'LU',u'442',u'Luxembourg'),
  (u'LV',u'428',u'Latvia'),
  (u'LY',u'434',u'Libya'),
  (u'MA',u'504',u'Morocco'),
  (u'MC',u'492',u'Monaco'),
  (u'MD',u'498',u'Moldova'),
  (u'ME',u'499',u'Montenegro'),
  (u'MF',u'663',u'St. Martin'),
  (u'MG',u'450',u'Madagascar'),
  (u'MH',u'584',u'Marshall Islands'),
  (u'MK',u'807',u'Macedonia'),
  (u'ML',u'466',u'Mali'),
  (u'MM',u'104',u'Myanmar'),
  (u'MN',u'496',u'Mongolia'),
  (u'MO',u'446',u'Macao'),
  (u'MP',u'580',u'Northern Mariana Islands'),
  (u'MQ',u'474',u'Martinique'),
  (u'MR',u'478',u'Mauritania'),
  (u'MS',u'500',u'Montserrat'),
  (u'MT',u'470',u'Malta'),
  (u'MU',u'480',u'Mauritius'),
  (u'MV',u'462',u'Maldives'),
  (u'MW',u'454',u'Malawi'),
  (u'MX',u'484',u'Mexico'),
  (u'MY',u'458',u'Malaysia'),
  (u'MZ',u'508',u'Mozambique'),
  (u'NA',u'516',u'Namibia'),
  (u'NC',u'540',u'New Caledonia'),
  (u'NE',u'562',u'Niger'),
  (u'NF',u'574',u'Norfolk Island'),
  (u'NG',u'566',u'Nigeria'),
  (u'NI',u'558',u'Nicaragua'),
  (u'NL',u'528',u'Netherlands, The'),
  (u'NO',u'578',u'Norway'),
  (u'NP',u'524',u'Nepal'),
  (u'NR',u'520',u'Nauru'),
  (u'NU',u'570',u'Niue'),
  (u'NZ',u'554',u'New Zealand'),
  (u'OM',u'512',u'Oman'),
  (u'PA',u'591',u'Panama'),
  (u'PE',u'604',u'Peru'),
  (u'PF',u'258',u'French Polynesia'),
  (u'PG',u'598',u'Papua New Guinea'),
  (u'PH',u'608',u'Philippines'),
  (u'PK',u'586',u'Pakistan'),
  (u'PL',u'616',u'Poland'),
  (u'PM',u'666',u'St. Pierre and Miquelon'),
  (u'PN',u'612',u'Pitcairn'),
  (u'PR',u'630',u'Puerto Rico'),
  (u'PS',u'275',u'Palestinian Authority'),
  (u'PT',u'620',u'Portugal'),
  (u'PW',u'585',u'Palau'),
  (u'PY',u'600',u'Paraguay'),
  (u'QA',u'634',u'Qatar'),
  (u'RE',u'638',u'Reunion'),
  (u'RO',u'642',u'Romania'),
  (u'RS',u'688',u'Serbia'),
  (u'RU',u'643',u'Russia'),
  (u'RW',u'646',u'Rwanda'),
  (u'SA',u'682',u'Saudi Arabia'),
  (u'SB',u'90', u'Solomon Islands'),
  (u'SC',u'690',u'Seychelles'),
  (u'SD',u'736',u'Sudan'),
  (u'SE',u'752',u'Sweden'),
  (u'SG',u'702',u'Singapore'),
  (u'SH',u'654',u'St. Helena'),
  (u'SI',u'705',u'Slovenia'),
  (u'SJ',u'744',u'Svalbard and Jan Mayen'),
  (u'SK',u'703',u'Slovakia'),
  (u'SL',u'694',u'Sierra Leone'),
  (u'SM',u'674',u'San Marino'),
  (u'SN',u'686',u'Senegal'),
  (u'SO',u'706',u'Somalia'),
  (u'SR',u'740',u'Suriname'),
  (u'SS',u'728',u'South Sudan'),
  (u'ST',u'678',u'São Tomé und Príncipe'),
  (u'SV',u'222',u'El Salvador'),
  (u'SY',u'760',u'Syria'),
  (u'SZ',u'748',u'Swaziland'),
  (u'TC',u'796',u'Turks and Caicos Islands'),
  (u'TD',u'148',u'Chad'),
  (u'TF',u'260',u'French Southern and Antarctic Lands'),
  (u'TG',u'768',u'Togo'),
  (u'TH',u'764',u'Thailand'),
  (u'TJ',u'762',u'Tajikistan'),
  (u'TK',u'772',u'Tokelau'),
  (u'TM',u'795',u'Turkmenistan'),
  (u'TN',u'788',u'Tunisia'),
  (u'TO',u'776',u'Tonga'),
  (u'TL',u'626',u'Timor-Leste'),
  (u'TR',u'792',u'Turkey'),
  (u'TT',u'780',u'Trinidad and Tobago'),
  (u'TV',u'798',u'Tuvalu'),
  (u'TW',u'158',u'Taiwan'),
  (u'TZ',u'834',u'Tanzania'),
  (u'UA',u'804',u'Ukraine'),
  (u'UG',u'800',u'Uganda'),
  (u'UM',u'581',u'United States Minor Outlying Islands'),
  (u'US',u'840',u'United States'),
  (u'UY',u'858',u'Uruguay'),
  (u'UZ',u'860',u'Uzbekistan'),
  (u'VA',u'336',u'Vatican City'),
  (u'VC',u'670',u'St. Vincent and the Grenadines'),
  (u'VE',u'862',u'Venezuela'),
  (u'VG',u'92', u'Virgin Islands, British'),
  (u'VI',u'850',u'Virgin Islands, U.S.'),
  (u'VN',u'704',u'Viet Nam'),
  (u'VU',u'548',u'Vanuatu'),
  (u'WF',u'876',u'Wallis and Futuna'),
  (u'WS',u'882',u'Samoa'),
  (u'YE',u'887',u'Yemen'),
  (u'YT',u'175',u'Mayotte'),
  (u'YU',u'891',u'Serbia and Montenegro (obsolete)'),
  (u'ZA',u'710',u'South Africa'),
  (u'ZM',u'894',u'Zambia'),
  (u'ZW',u'716',u'Zimbabwe'),
)

# Intialize dictionary-based mappings
c_dict = {}
countryCode_dict = {}
for c,countryCode,country_name in countries:
  c_dict[c] = country_name
  countryCode_dict[countryCode] = country_name
